use std::fmt::Write;
use std::path::PathBuf;

/// A Frost type that a parameter can accept.
#[derive(Clone, Copy)]
pub enum Type {
    Int,
    Float,
    Bool,
    String,
    Array,
    Map,
    Function,
    /// Accepts any type.
    Any,
}

impl Type {
    fn cpp_type_name(self) -> &'static str {
        match self {
            Type::Int => "Int",
            Type::Float => "Float",
            Type::Bool => "Bool",
            Type::String => "String",
            Type::Array => "Array",
            Type::Map => "Map",
            Type::Function => "Function",
            Type::Any => unreachable!("Any has no single C++ type name"),
        }
    }
}

/// A single parameter spec for REQUIRE_ARGS.
pub struct Param {
    label: &'static str,
    types: Vec<Type>,
}

impl Param {
    fn is_single_primitive(&self) -> bool {
        self.types.len() == 1
            && matches!(
                self.types[0],
                Type::Int | Type::Float | Type::Bool | Type::String
            )
    }
}

/// Whether a parameter is required, optional, or variadic rest.
pub enum ParamKind {
    Required(Param),
    Optional(Param),
    VariadicRest {
        label: &'static str,
        types: Vec<Type>,
        min_count: usize,
    },
}

/// A function to be exported from a Rust extension.
pub struct FunctionSpec {
    name: &'static str,
    params: Vec<ParamKind>,
}

impl FunctionSpec {
    fn new(name: &'static str) -> Self {
        Self {
            name,
            params: Vec::new(),
        }
    }

    /// Add a required parameter that accepts one or more types.
    pub fn param(&mut self, label: &'static str, types: &[Type]) -> &mut Self {
        self.params.push(ParamKind::Required(Param {
            label,
            types: types.to_vec(),
        }));
        self
    }

    /// Add an optional parameter.
    pub fn optional(&mut self, label: &'static str, types: &[Type]) -> &mut Self {
        self.params.push(ParamKind::Optional(Param {
            label,
            types: types.to_vec(),
        }));
        self
    }

    /// Add a variadic rest parameter (must be last).
    pub fn variadic_rest(
        &mut self,
        label: &'static str,
        types: &[Type],
        min_count: usize,
    ) -> &mut Self {
        self.params.push(ParamKind::VariadicRest {
            label,
            types: types.to_vec(),
            min_count,
        });
        self
    }

    /// Add a required parameter that accepts any type.
    pub fn any(&mut self, label: &'static str) -> &mut Self {
        self.params.push(ParamKind::Required(Param {
            label,
            types: vec![Type::Any],
        }));
        self
    }
}

/// Builder for a Rust-backed Frost extension.
///
/// Generates three artifacts:
/// - A C++ file with BUILTIN shims and REGISTER_EXTENSION (compiled by CMake)
/// - A Rust bridge file with the cxx bridge and wrapper functions (included by
///   the extension crate)
/// - The cxx-build compilation of the bridge
pub struct ExtensionBuilder {
    name: &'static str,
    functions: Vec<FunctionSpec>,
    glue_include_dir: PathBuf,
}

impl ExtensionBuilder {
    pub fn new(name: &'static str, glue_include_dir: PathBuf) -> Self {
        Self {
            name,
            functions: Vec::new(),
            glue_include_dir,
        }
    }

    /// Declare an exported function. Returns a mutable reference for adding
    /// params.
    pub fn function(&mut self, name: &'static str) -> &mut FunctionSpec {
        self.functions.push(FunctionSpec::new(name));
        self.functions.last_mut().unwrap()
    }

    /// Generate all artifacts and run cxx-build.
    pub fn generate(&self) {
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

        let cpp = self.generate_cpp();
        let cpp_path = out_dir.join(format!("{}.cpp", self.name));
        std::fs::write(&cpp_path, &cpp).unwrap();

        let bridge_rs = self.generate_bridge_rs();
        let bridge_path = out_dir.join("bridge.rs");
        std::fs::write(&bridge_path, &bridge_rs).unwrap();

        cxx_build::bridge(&bridge_path)
            .include(&self.glue_include_dir)
            .compile(format!("{}-cxxbridge", self.name));

        println!("cargo:rerun-if-changed=build.rs");
    }

    // -- C++ codegen --

    fn generate_cpp(&self) -> String {
        let mut out = String::new();
        let ext = self.name;

        writeln!(out, "// Generated by frost-glue-build -- do not edit").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#include <frost/extensions-common.hpp>").unwrap();
        writeln!(out, "#include <rust/cxx.h>").unwrap();
        writeln!(out).unwrap();

        // Forward-declare the cxx-generated Rust wrapper functions.
        self.write_cpp_forward_declarations(&mut out);

        writeln!(out).unwrap();
        writeln!(out, "namespace frst").unwrap();
        writeln!(out, "{{").unwrap();
        writeln!(out, "namespace {ext}").unwrap();
        writeln!(out, "{{").unwrap();
        writeln!(out, "namespace").unwrap();
        writeln!(out, "{{").unwrap();

        for func in &self.functions {
            writeln!(out).unwrap();
            self.write_cpp_builtin(&mut out, func);
        }

        writeln!(out).unwrap();
        writeln!(out, "}} // anon namespace").unwrap();
        writeln!(out, "}} // namespace {ext}").unwrap();
        writeln!(out).unwrap();

        // Registration
        write!(out, "REGISTER_EXTENSION({ext}").unwrap();
        for func in &self.functions {
            write!(out, ", ENTRY({})", func.name).unwrap();
        }
        writeln!(out, ")").unwrap();

        writeln!(out).unwrap();
        writeln!(out, "}} // namespace frst").unwrap();

        out
    }

    fn write_cpp_forward_declarations(&self, out: &mut String) {
        let ext = self.name;

        writeln!(out, "namespace frst::rs::{ext}").unwrap();
        writeln!(out, "{{").unwrap();

        for func in &self.functions {
            let name = func.name;
            write!(
                out,
                "::std::shared_ptr<::frst::rs::Value> rust_{ext}_{name}("
            )
            .unwrap();

            let mut first = true;
            for (i, pk) in func.params.iter().enumerate() {
                match pk {
                    ParamKind::Required(p) | ParamKind::Optional(p) => {
                        if !first {
                            write!(out, ", ").unwrap();
                        }
                        first = false;
                        write!(out, "{} arg{i}", cpp_param_type(p)).unwrap();
                    }
                    ParamKind::VariadicRest { .. } => {
                        if !first {
                            write!(out, ", ").unwrap();
                        }
                        first = false;
                        write!(
                            out,
                            "::rust::Vec<::std::shared_ptr<::frst::rs::Value>> const &rest"
                        )
                        .unwrap();
                    }
                }
            }

            writeln!(out, ");").unwrap();
        }

        writeln!(out, "}} // namespace frst::rs::{ext}").unwrap();
    }

    fn write_cpp_builtin(&self, out: &mut String, func: &FunctionSpec) {
        let ext = self.name;
        let name = func.name;
        let qualified = format!("{ext}.{name}");

        writeln!(out, "BUILTIN({name})").unwrap();
        writeln!(out, "{{").unwrap();

        // REQUIRE_ARGS
        write!(out, "    REQUIRE_ARGS(\"{qualified}\"").unwrap();
        for pk in &func.params {
            write!(out, ", ").unwrap();
            match pk {
                ParamKind::Required(p) => {
                    write!(out, "PARAM(\"{}\", {})", p.label, types_macro(&p.types))
                        .unwrap();
                }
                ParamKind::Optional(p) => {
                    write!(
                        out,
                        "OPTIONAL(PARAM(\"{}\", {}))",
                        p.label,
                        types_macro(&p.types)
                    )
                    .unwrap();
                }
                ParamKind::VariadicRest {
                    label,
                    types,
                    min_count,
                } => {
                    write!(
                        out,
                        "VARIADIC_REST({min_count}, \"{label}\", {})",
                        types_macro(types)
                    )
                    .unwrap();
                }
            }
        }
        writeln!(out, ");").unwrap();

        // Call into Rust, catching rust::Error
        writeln!(out, "    try {{").unwrap();
        write!(out, "        return frst::rs::{ext}::rust_{ext}_{name}(").unwrap();

        let mut first = true;
        for (i, pk) in func.params.iter().enumerate() {
            match pk {
                ParamKind::Required(p) | ParamKind::Optional(p) => {
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(out, "{}", cpp_arg_extract(i, p)).unwrap();
                }
                ParamKind::VariadicRest { .. } => {
                    // Collect remaining args into a rust::Vec
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(out, "[&]() {{ ::rust::Vec<Value_Ptr> v; for (auto j = {i}u; j < args.size(); ++j) v.push_back(args[j]); return v; }}()").unwrap();
                }
            }
        }

        writeln!(out, ");").unwrap();
        writeln!(
            out,
            "    }} catch (const ::rust::Error& e) {{"
        )
        .unwrap();
        writeln!(
            out,
            "        throw Frost_Recoverable_Error{{std::string(e.what())}};"
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
    }

    // -- Rust codegen --

    fn generate_bridge_rs(&self) -> String {
        let mut out = String::new();
        let ext = self.name;

        writeln!(out, "// Generated by frost-glue-build -- do not edit").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#[cxx::bridge(namespace = \"frst::rs::{ext}\")]").unwrap();
        writeln!(out, "mod ffi {{").unwrap();
        writeln!(out, "    unsafe extern \"C++\" {{").unwrap();
        writeln!(out, "        include!(\"frost-glue.hpp\");").unwrap();
        writeln!(out, "        type Value;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    extern \"Rust\" {{").unwrap();

        for func in &self.functions {
            let name = func.name;
            write!(
                out,
                "        fn rust_{ext}_{name}("
            )
            .unwrap();

            let mut first = true;
            for (i, pk) in func.params.iter().enumerate() {
                match pk {
                    ParamKind::Required(p) | ParamKind::Optional(p) => {
                        if !first {
                            write!(out, ", ").unwrap();
                        }
                        first = false;
                        write!(out, "arg{i}: {}", rust_bridge_param_type(p)).unwrap();
                    }
                    ParamKind::VariadicRest { .. } => {
                        if !first {
                            write!(out, ", ").unwrap();
                        }
                        first = false;
                        write!(out, "rest: &Vec<SharedPtr<Value>>").unwrap();
                    }
                }
            }

            writeln!(out, ") -> Result<SharedPtr<Value>>;").unwrap();
        }

        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();

        // Wrapper functions that convert between cxx types and FrostValue
        for func in &self.functions {
            writeln!(out).unwrap();
            self.write_rust_wrapper(&mut out, func);
        }

        out
    }

    fn write_rust_wrapper(&self, out: &mut String, func: &FunctionSpec) {
        let ext = self.name;
        let name = func.name;

        // Signature matching the cxx bridge declaration
        write!(out, "fn rust_{ext}_{name}(").unwrap();

        let mut first = true;
        for (i, pk) in func.params.iter().enumerate() {
            match pk {
                ParamKind::Required(p) | ParamKind::Optional(p) => {
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(out, "arg{i}: {}", rust_bridge_param_type(p)).unwrap();
                }
                ParamKind::VariadicRest { .. } => {
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(out, "rest: &Vec<cxx::SharedPtr<ffi::Value>>").unwrap();
                }
            }
        }

        writeln!(
            out,
            ") -> Result<cxx::SharedPtr<ffi::Value>, String> {{"
        )
        .unwrap();

        // Call the user's function with converted arguments
        write!(out, "    let result = {name}(").unwrap();

        let mut first = true;
        for (i, pk) in func.params.iter().enumerate() {
            match pk {
                ParamKind::Required(p) | ParamKind::Optional(p) => {
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(out, "{}", rust_arg_convert(i, p)).unwrap();
                }
                ParamKind::VariadicRest { .. } => {
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(
                        out,
                        "&rest.iter().map(|v| frost_glue::FrostValue::from_shared(\
                         unsafe {{ std::mem::transmute(v.clone()) }}\
                         )).collect::<Vec<_>>()"
                    )
                    .unwrap();
                }
            }
        }

        writeln!(out, ")?;").unwrap();
        // Transmute SharedPtr<frost_glue::ffi::Value> -> SharedPtr<ffi::Value>
        // Both are the same C++ type (frst::rs::Value = const frst::Value).
        writeln!(
            out,
            "    Ok(unsafe {{ std::mem::transmute(result.into_shared()) }})"
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
    }

    fn has_variadic(&self, func: &FunctionSpec) -> bool {
        func.params
            .iter()
            .any(|p| matches!(p, ParamKind::VariadicRest { .. }))
    }
}

// -- Type mapping helpers --

/// C++ parameter type in the forward declaration.
fn cpp_param_type(p: &Param) -> &'static str {
    if p.is_single_primitive() {
        match p.types[0] {
            Type::Int => "::std::int64_t",
            Type::Float => "double",
            Type::Bool => "bool",
            Type::String => "::std::string const &",
            _ => unreachable!(),
        }
    } else {
        "::std::shared_ptr<::frst::rs::Value>"
    }
}

/// C++ expression to extract an arg for the Rust call.
fn cpp_arg_extract(i: usize, p: &Param) -> String {
    if p.is_single_primitive() {
        match p.types[0] {
            Type::Int => format!("GET({i}, Int)"),
            Type::Float => format!("GET({i}, Float)"),
            Type::Bool => format!("GET({i}, Bool)"),
            Type::String => format!("GET({i}, String)"),
            _ => unreachable!(),
        }
    } else {
        format!("args[{i}]")
    }
}

/// Rust type for a parameter in the cxx bridge declaration.
fn rust_bridge_param_type(p: &Param) -> &'static str {
    if p.is_single_primitive() {
        match p.types[0] {
            Type::Int => "i64",
            Type::Float => "f64",
            Type::Bool => "bool",
            Type::String => "&CxxString",
            _ => unreachable!(),
        }
    } else {
        "SharedPtr<Value>"
    }
}

/// Rust expression to convert a bridge param into the user function's type.
fn rust_arg_convert(i: usize, p: &Param) -> String {
    if p.is_single_primitive() {
        match p.types[0] {
            Type::Int | Type::Float | Type::Bool => format!("arg{i}"),
            Type::String => {
                format!("arg{i}.to_str().map_err(|e| e.to_string())?")
            }
            _ => unreachable!(),
        }
    } else {
        format!("frost_glue::FrostValue::from_shared(unsafe {{ std::mem::transmute(arg{i}) }})")
    }
}

fn types_macro(types: &[Type]) -> String {
    if types.len() == 1 && matches!(types[0], Type::Any) {
        return "ANY".to_owned();
    }

    let inner: Vec<&str> = types.iter().map(|t| t.cpp_type_name()).collect();
    format!("TYPES({})", inner.join(", "))
}
