//! Keeps the runtime's generated globals in step with their Frost source.
//!
//! Some globals are written in Frost. The runtime can use the compiler only in
//! its tests, so this test compiles their source and renders the result as Rust,
//! into the checked-in `compiled.rs` beside the source. It fails while that file
//! differs from what the current source and compiler produce. Set
//! `UPDATE_GENERATED` to rewrite the file instead:
//!
//! ```text
//! UPDATE_GENERATED=1 cargo test -p frost-runtime --test generated_globals
//! ```
//!
//! The runtime's `generated` module documents the other side: what `compiled.rs`
//! holds, and how the runtime loads it.

use std::collections::{BTreeMap, BTreeSet};
use std::{env, fs};

use frost_compile::{CompilerOptions, OptimizationOptions, compile_in_scope};
use frost_runtime::{CompiledFunction, GLOBAL_NAMES, MapKey, Value, from_value, to_value};

const SOURCE: &str = include_str!("../src/vm/globals/generated/source.frst");

const COMPILED_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/vm/globals/generated/compiled.rs"
);

/// Every optimization but constant folding. Folding runs calls to globals at
/// compile time, and those include the globals generated here: the output would
/// depend on the previous `compiled.rs`, and a stale one cannot even be loaded.
const OPTIONS: CompilerOptions = CompilerOptions {
    optimization_options: OptimizationOptions {
        constant_fold: false,
        ..OptimizationOptions::ALL
    },
    implicit_export: false,
};

/// The line width the rendered Rust aims to stay within.
const WIDTH: usize = 100;

#[test]
fn compiled_generated_globals_match_their_source() {
    let expected = generate(SOURCE);
    let actual = fs::read_to_string(COMPILED_PATH).unwrap_or_default();
    if actual == expected {
        return;
    }
    if env::var_os("UPDATE_GENERATED").is_some() {
        fs::write(COMPILED_PATH, expected).expect("compiled.rs is writable");
        return;
    }
    panic!(
        "{COMPILED_PATH} is stale: it differs from what its source and the current compiler \
         produce. Regenerate it with:\n\n    \
         UPDATE_GENERATED=1 cargo test -p frost-runtime --test generated_globals\n"
    );
}

/// The full text of `compiled.rs` for `source`.
fn generate(source: &str) -> String {
    let output = compile_in_scope("source.frst", source, OPTIONS, &[]).unwrap_or_else(|errors| {
        panic!(
            "the generated globals' source does not compile:\n{}",
            errors.render_plain()
        )
    });
    let program = output
        .code
        .close(BTreeMap::new())
        .expect("the source's top level captures nothing");
    let functions = &program.inner_fn().child_fns;
    check(functions);

    let tree: Value = functions
        .iter()
        .map(|function| {
            let value = to_value(function.as_ref()).unwrap_or_else(|err| {
                panic!("`{}` does not serialize: {}", function.name, err.message())
            });
            check_round_trip(function, &value);
            (MapKey::from(function.name.as_str()), value)
        })
        .collect();

    let listings: Vec<String> = functions
        .iter()
        .map(|function| function.disassemble().to_string())
        .collect();
    let listing: String = listings
        .join("\n")
        .lines()
        .map(|line| format!("// {line}").trim_end().to_owned() + "\n")
        .collect();

    format!(
        r"// @generated by the `generated_globals` test in `frost-runtime`. Do not edit.
//
// The listing of each function, for review:
//
{listing}
use crate::Value;

use super::build::*;

pub(super) fn functions() -> Value {{
    {}
}}
",
        render(&tree, 1)
    )
}

/// Panic unless each of `functions` can be a global: named for a global, named
/// once, and without captures.
fn check(functions: &[std::sync::Arc<CompiledFunction>]) {
    let mut seen = BTreeSet::new();
    for function in functions {
        let name = function.name.as_str();
        assert!(
            GLOBAL_NAMES.contains(&name),
            "`{name}` in the generated globals' source is not a global; add it to `define_globals!`"
        );
        assert!(seen.insert(name), "`{name}` is defined more than once");
        let captures: Vec<&str> = function.capture_names().collect();
        assert!(
            captures.is_empty(),
            "`{name}` captures {captures:?}, but a global cannot capture: \
             it may refer only to its parameters, its own name, and globals"
        );
    }
}

/// Panic unless `encoded`, the serde bridge's form of `function`, decodes as the
/// runtime decodes it into a function with the same disassembly.
fn check_round_trip(function: &CompiledFunction, encoded: &Value) {
    let name = &function.name;
    let decoded = from_value::<CompiledFunction>(encoded.clone())
        .unwrap_or_else(|err| panic!("`{name}` does not decode: {}", err.message()));
    assert_eq!(
        decoded.disassemble().to_string(),
        function.disassemble().to_string(),
        "`{name}` changes in a round trip through the serde bridge"
    );
}

/// A Rust expression building `value` from the constructors in the runtime's
/// `generated::build`, laid out for an indentation of `indent` levels.
fn render(value: &Value, indent: usize) -> String {
    let flat = render_flat(value);
    if indent * 4 + flat.len() <= WIDTH {
        return flat;
    }
    let inner = "    ".repeat(indent + 1);
    let outer = "    ".repeat(indent);
    match value {
        Value::Array(elements) => {
            let lines: String = elements
                .iter()
                .map(|element| format!("{inner}{},\n", render(element, indent + 1)))
                .collect();
            format!("array([\n{lines}{outer}])")
        }
        Value::Map(_) => {
            let lines: String = sorted_entries(value)
                .into_iter()
                .map(|(key, value)| {
                    let key = render_flat(&Value::from(key.clone()));
                    format!("{inner}({key}, {}),\n", render(value, indent + 1))
                })
                .collect();
            format!("map([\n{lines}{outer}])")
        }
        // Too long, but nothing to break.
        _ => flat,
    }
}

/// [`render`] on one line.
fn render_flat(value: &Value) -> String {
    match value {
        Value::Null => "null()".to_string(),
        Value::Bool(b) => format!("boolean({b})"),
        Value::Int(i) => format!("int({i})"),
        Value::Float(f) => format!("float({:#018x})", f.get().to_bits()),
        Value::String(text) => format!("string({:?})", text.as_ref()),
        Value::Bytes(octets) => {
            let octets: Vec<String> = octets.iter().map(|octet| format!("{octet:#04x}")).collect();
            format!("bytes(&[{}])", octets.join(", "))
        }
        Value::Array(elements) => {
            let elements: Vec<String> = elements.iter().map(render_flat).collect();
            format!("array([{}])", elements.join(", "))
        }
        Value::Map(_) => {
            let entries: Vec<String> = sorted_entries(value)
                .into_iter()
                .map(|(key, value)| {
                    format!(
                        "({}, {})",
                        render_flat(&Value::from(key.clone())),
                        render_flat(value)
                    )
                })
                .collect();
            format!("map([{}])", entries.join(", "))
        }
        Value::NativeFunction(_) | Value::Closure(_) | Value::Opaque(_) => {
            panic!(
                "a serialized function holds only data, not {}",
                value.type_name()
            )
        }
    }
}

/// A Map's entries in key order, so the rendering depends only on its contents.
fn sorted_entries(map: &Value) -> Vec<(&MapKey, &Value)> {
    let Value::Map(map) = map else {
        unreachable!("only a Map has entries")
    };
    let mut entries: Vec<_> = map.iter().collect();
    entries.sort_by_key(|(key, _)| *key);
    entries
}
