[package]
name = "frostlang-cli"
version = "0.0.1"
edition.workspace = true

[[bin]]
name = "frost"
path = "src/main.rs"

[dependencies]
frostlang-driver = { workspace = true, features = ["graphical-diagnostics"] }
frostlang-fs-resolver = { workspace = true, features = ["graphical-diagnostics"] }
frostlang-runtime.workspace = true

[lints]
workspace = true
